server:
  port: DYNAMICPORT
  address: 0.0.0.0
spring:
  main:
    banner-mode: log
lavalink:
  server:
    password: michaelnguyen
    sources:
      youtube: true
      bandcamp: false
      soundcloud: true
      twitch: false
      vimeo: true
      mixer: false
      http: true
      local: true
    bufferDurationMs: 400
    youtubePlaylistLoadLimit: 500
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: true

metrics:
  prometheus:
    enabled: false
    endpoint: /metrics

sentry:
  dsn: ""

logging:
  file:
    max-history: 1
    max-size: 3MB
  path: /app/logs/

  level:
    root: INFO
    lavalink: INFO
